### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by Rozin14** [openpst/sahara#16]
I kave no errors. But i want to know how it works. 

When we use a firehose.elf file to access partition of a device, is the firehose file fully transferred to the device or is it's some part  used up by qfil to access partition?

**Comment by ghassani** [comment]
If you have a valid firehose programmer for your device and you use this tool to send it to your device and then send the done command, you can use any program that speaks firehose to fix your device after this. Sadly, most of these tools want to provision the image itself and if its already in firehose mode then it probably wont work but I am not sure about all tools, but definitely QFIL wont work.

My suggestion is, if you have a valid programmer and recovery files just use another program which supports firehose. I do not think I will ever add firehose support to openpst since I do not really work on this project anymore sadly.

But basically the phone in EDL sahara mode starts off in PBL, then it requests an image (for example your firehose image) - you then upload it and send the done command and if it was valid for your device configuration (ie valid signature and valid SoC version) then the phone will transfer execution to the uploaded program. This could be firehose or some other protocol it all depends on the OEM.
